name: chantier_manager
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.26
  path_provider: ^2.1.5
  path: ^1.9.0
  supabase_flutter: ^2.8.2
  workmanager: ^0.5.2
  geolocator: ^13.0.2
  image_picker: ^1.1.2
  flutter_sound: ^9.16.8
  permission_handler: ^11.3.1
  intl: ^0.19.0
  uuid: ^4.5.2
  go_router: ^14.6.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  sqlite3_web: ^0.1.0
  excel: ^4.0.6
  pdf: ^3.11.3
  printing: ^5.14.2
  file_picker: ^8.1.7
  universal_html: ^2.3.0
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  drift_dev: ^2.24.2
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
